backend:
  name: git-gateway
  branch: master
media_folder: static/img
collections:
  - name: 'pages'
    label: 'Pages'
    files:
      - label: 'Home'
        name: 'home'
        file: 'content/home.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Slogan', name: 'slogan', widget: 'string' }
          - { label: 'About', name: 'about', widget: 'string' }
